#!/usr/bin/env bash
# comment 

# "$1" "testfile.txt"
# "$2" "34.75.134.83"
# "$3" "ubuntu"
# "$4" "/ssh/holberton"

if [ "$#" -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":/~
fi

