#!/usr/bin/env bash
# configuring web 02

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/ a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
Server_name=$(hostname)
sudo sed -i "/http {/ a \\\tadd_header X-Served-By $Server_name;" /etc/nginx/nginx.conf
sudo service nginx restart