#!/usr/bin/env bash
# configuring web 02

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i "8i ENABLED=1" /etc/default/haproxy
sudo chmod 755 /etc/default/haproxy
sudo sed -i "$ a frontend http_front\n\tbind *:80\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 2695-web-01 34.75.134.83:80 check\n\tserver 2695-web-02 3.85.205.247:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
