#!/usr/bin/env bash
# script that configure your Nginx server so that /redirect_me is redirecting to another page
sudo service nginx stop
sudo sed -i 's/ipv6only=on//g' /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
