#!/usr/bin/env bash
# This script is displaying /etc/content
FILENAME="/etc/passwd"
while IFS=: read -r username userid comment homedir
do 
    echo "$username:$userid:$comment:$homedir"

done < $FILENAME
