#!/usr/bin/env bash
# This script is displaying a history
FILENAME="/etc/passwd"
while IFS=: read -r USERNAME GROUP_ID HOME_DIRECTORY COMMAND SHELL USERID PASSWORD USERIDINFO
do 
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/$SHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"

done < $FILENAME
