#!/usr/bin/env bash
# This script is displaying the number from 1 to 20
x=0
y=0
while [ $x -le 12 ]
do
    echo "Hour: $x"
    while [ $y -le 60 ]
    do
        echo $y
        y=$((y+1))
    done
    y=0
    x=$((x+1))
done